
CREATE TABLE ORGANIZATIONS (
ID_ORGANIZATION VARCHAR(255) NOT NULL PRIMARY KEY,
NAME VARCHAR(255),
COMMENTS VARCHAR(255)
);

CREATE TABLE EMPLOYEES (
ID_ORGANIZATION VARCHAR(255),
DATE_HIRE DATE,
ID_EMPLOYEE VARCHAR(255) NOT NULL PRIMARY KEY,
DATE_TERMINATION DATE,
DATE_BIRTH DATE,
CONSTRAINT FN_EMPLOYEES_ORGANIZATIONS FOREIGN KEY (ID_ORGANIZATION) REFERENCES ORGANIZATIONS(ID_ORGANIZATION)
);

CREATE TABLE USERS (
ID_USER VARCHAR(255) NOT NULL PRIMARY KEY,
ID_LOGIN VARCHAR(255),
ID_EMPLOYEE VARCHAR(255),
DT_LAST_CONNECT DATETIME2,
MAX_ATTEMPS INT,
BLOCKED TINYINT DEFAULT 0,
BLOCKED_TIME DATETIME2,
NUM_ATTEMPS INT,
CONSTRAINT FK_USERS_EMPLOYEES FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEES(ID_EMPLOYEE)
);

CREATE TABLE PERSON (
ID_PERSON VARCHAR(255) NOT NULL PRIMARY KEY,
ID_ORGANIZATION VARCHAR(255),
NAME VARCHAR(255),
SURNAME VARCHAR(255),
SECOND_NAME VARCHAR(255),
EMAIL VARCHAR(255),
NIF VARCHAR(255),
CONSTRAINT FN_PERSON_ORGANIZATION FOREIGN KEY (ID_ORGANIZATION) REFERENCES ORGANIZATIONS(ID_ORGANIZATION),
);

CREATE TABLE TP_PHONE (
ID_TYPE VARCHAR(255) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(255)
);

CREATE TABLE PHONE (
ID_PERSON VARCHAR(255) PRIMARY KEY,
ORDINAL INT IDENTITY(1,1),
TP_PHONE VARCHAR(255),
CONSTRAINT FN_PHONE_TO_TP_PHONE FOREIGN KEY (TP_PHONE) REFERENCES TP_PHONE(ID_TYPE),
CONSTRAINT FN_PHONE_PERSON FOREIGN KEY (ID_PERSON) REFERENCES PERSON(ID_PERSON)
);

CREATE TABLE ENDPOINTS_AUDIT (
ID_ENDPOINTS INT IDENTITY(1,1) PRIMARY KEY,
ID_USER VARCHAR(255),
DATE_REGISTER DATETIME,
RESPONSE VARCHAR(255),
CONSTRAINT FN_ENDPOINTS_USERS FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
);

CREATE TABLE ENDPOINTS (
ID_ENDPOINTS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(255),
DESCRIPTION VARCHAR(255),
CONSTRAINT FN_ENDPOINTS FOREIGN KEY (ID_ENDPOINTS) REFERENCES ENDPOINTS_AUDIT
);
